#!/usr/bin/env bash

#set -o errtrace
#set -o errexit
#
#export PS4='+[${BASH_SOURCE}] : ${LINENO} : ${FUNCNAME[0]:+${FUNCNAME[0]}() $ }'

url="github.com/rocksolidwebdesign/Ubuntu-Server-In-A-Box.git"
git_url="git://$url"
https_url="https://$url"

if ! git clone "$git_url" ; then
    printf "\nERROR: Error using $git_url"

    if ! git clone "$https_url" ; then
        printf "\nERROR: Error using $https_url also. Guess you'll have to install manually."
        exit 1
    fi
fi

cd Ubuntu-Server-In-A-Box
if [ ! $(which fab) ] ; then
    if [ "$VIRTUAL_ENV" != "" ]; then
        # if the user is currently in a virtual environment then use that
        pip install -r requirements.txt
    else
        printf "\nIt looks like you don't have Fabric installed, please enter your local administration password to install Fabric...\n"

        # otherwise, install fabric system wide
        sudo pip install -r requirements.txt
    fi
fi

cd maverick_cloud
cp settings.py.sample settings.py
